config/routes.rb
Rails.application.routes.draw do
  resources :editions
  resources :books
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'books#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  
  belongs_to :edition

end

app/models/edition.rb
class Edition < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :releaseDate, :Cover, :publishingCompany, :ISBNTen, :author, :edition_id)
    end
end

app/controllers/editions_controller.rb
class EditionsController < ApplicationController
  before_action :set_edition, only: %i[ show edit update destroy ]

  # GET /editions or /editions.json
  def index
    @editions = Edition.all
  end

  # GET /editions/1 or /editions/1.json
  def show
  end

  # GET /editions/new
  def new
    @edition = Edition.new
  end

  # GET /editions/1/edit
  def edit
  end

  # POST /editions or /editions.json
  def create
    @edition = Edition.new(edition_params)

    respond_to do |format|
      if @edition.save
        format.html { redirect_to edition_url(@edition), notice: "Edition was successfully created." }
        format.json { render :show, status: :created, location: @edition }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @edition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /editions/1 or /editions/1.json
  def update
    respond_to do |format|
      if @edition.update(edition_params)
        format.html { redirect_to edition_url(@edition), notice: "Edition was successfully updated." }
        format.json { render :show, status: :ok, location: @edition }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @edition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /editions/1 or /editions/1.json
  def destroy
    @edition.destroy

    respond_to do |format|
      format.html { redirect_to editions_url, notice: "Edition was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_edition
      @edition = Edition.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def edition_params
      params.require(:edition).permit(:number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/editions_helper.rb
module EditionsHelper
end

app/views/books/_book.html.erb
   <div id="<%= dom_id book %>">

<div class='container'>
    <div class='card-group justify-content-center'>
      <div class="row row-cols-1 row-cols-md m-lg-4 g-4 mt-4">
        <div class="col-md-12 d-flex text-center ">
          <div class="card mb-3" style="max-width: 540px;">
            <div class="row g-0">
             <div class="col-md-4">
              <img src="<%= book.Cover %>" class="img-fluid rounded-start"alt="...">
            </div>
            <div class="col-md-6">
              <div class="card-body">
                <h5 class="card-title"><%= book.title %></h5>
                <p class="card-text">Data de lançamento: <%= book.releaseDate %></p>
                <p class="card-text">Editora: <%= book.publishingCompany %></p>
                <p class="card-text">ISBN10: <%= book.ISBNTen %></p>
                <p class="card-text">Autor: <%= book.author %> </p>
              </div>
            </div>
          </div>
        </div>      
      </div>
    </div>
  </div>
</div>
     


</div>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :releaseDate, style: "display: block" %>
    <%= form.date_field :releaseDate %>
  </div>

  <div>
    <%= form.label :Cover, style: "display: block" %>
    <%= form.text_field :Cover %>
  </div>

  <div>
    <%= form.label :publishingCompany, style: "display: block" %>
    <%= form.text_field :publishingCompany %>
  </div>

  <div>
    <%= form.label :ISBN10, style: "display: block" %>
    <%= form.number_field :ISBNTen %>
  </div>
  <div>
    <%= form.label :edition %>
    <%= collection_select(:book, :edition_id, Edition.all ,:id, :number)%>
  </div>


  <div>
    <%= form.label :author, style: "display: block" %>
    <%= form.text_field :author %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-12'>
      <h1 class='text-center'>Editar livro</h1>
    </div>
  </div>
</div>

  



<div>
  
</div>

<%= render "form", book: @book %>

<br>

<div>
  <button class='btn btn-outline-info'> <%= link_to "Mostrar Livro", @book %></button>
   |<button class='btn btn-outline-info'> <%= link_to "Voltar para Livros", books_path %></button>
 
</div>

app/views/books/index.html.erb
<p style="color: green"><%= notice %></p>
<div class='row'>
  <div class='col-md-12 text-center'>
    <h1 >Livros</h1>
  </div>
</div>

<div id="books">
       <% @books.each do |book| %>
    <%= render book %>
</div>
    <div class ="row justify-content-center ">
      <div class= "col-md-2 " >
            <button type="button" class="btn btn-outline-secondary"><%= link_to "Mostrar Livro", book %></button>
           
          
      </div>
    </div>

  <% end %>

    

     <div class ="row justify-content-center ">
      <div class= "col-md-3 " >
            <button type="button" class="btn btn-outline-secondary m-5"><%= link_to "Novo Livro", new_book_path %></button>

        
          
      </div>
    </div>

       
   

app/views/books/new.html.erb
<h1>Novo Livro</h1>

<%= render "form", book: @book %>

<br>

<div>
  <button> <%= link_to "Voltar para livros", books_path %></button>
  
</div>

app/views/books/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @book %>

<div>
  <%= link_to "Editar esse livro", edit_book_path(@book) %> |
  <%= link_to "Voltar para livros", books_path %>

  <%= button_to "Excluir", @book, method: :delete %>
</div>

app/views/editions/_edition.html.erb
<div id="<%= dom_id edition %>">
  <p>
    <strong>Numero:</strong>
    <%= edition.number %>
  </p>

</div>

app/views/editions/_form.html.erb
<%= form_with(model: edition) do |form| %>
  <% if edition.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(edition.errors.count, "error") %> prohibited this edition from being saved:</h2>

      <ul>
        <% edition.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :numero, style: "display: block" %>
    <%= form.text_field :number %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/editions/edit.html.erb
<h1>Editar edição</h1>

<%= render "form", edition: @edition %>

<br>

<div>
  <%= link_to "Mostrar edição", @edition %> |
  <%= link_to "Voltar para edições", editions_path %>
</div>

app/views/editions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Editions</h1>

<div id="editions">
  <% @editions.each do |edition| %>
    <%= render edition %>
    <p>
      <%= link_to "Mostrar edição", edition %>
    </p>
  <% end %>
</div>

<%= link_to "Nova edição", new_edition_path %>

app/views/editions/new.html.erb
<h1>Nova edição</h1>

<%= render "form", edition: @edition %>

<br>

<div>
  <%= link_to "Voltar para edições", editions_path %>
</div>

app/views/editions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @edition %>

<div>
  <%= link_to "Editar essa edição", edit_edition_path(@edition) %> |
  <%= link_to "Voltar para edição", editions_path %>

  <%= button_to "Excluir", @edition, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsRuby3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link rel="stylesheet" type="text/css" href="../app/assets/stylesheets/application.css" media="screen" />
      
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-info">
  <div class="container-fluid">
    <a class="navbar-brand" href="https://livraria-2.isatkmais.repl.co/books">Livraria</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="https://livraria-2.isatkmais.repl.co/books">Livros</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="https://livraria-2.isatkmais.repl.co/books/new">Novo Livro</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="https://livraria-2.isatkmais.repl.co/editions/new">Nova edição</a>
        </li>
      </ul>
    </div>
  </div>
      
</nav>
   <div id="carouselExampleFade" class="carousel slide carousel-fade">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="https://i.imgur.com/nL8PPbz.png" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="https://i.imgur.com/O9L9VfJ.jpeg" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="https://i.imgur.com/nL8PPbz.png" class="d-block w-100" alt="...">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
</div>
    
   <div class="container ">
     <div class = "row align-items-end">
       <div class = ".col-12 ">
             <%= yield %>
       </div>
     </div> 
    </div> 
    
  </body>
      
</html>